### ISSUE TITLE
Search box expansion does not allow clicking on links when it is NOT expanded

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#543]
FYI @derickbailey 
![image](https://user-images.githubusercontent.com/63502/34699817-17254ac8-f4a5-11e7-86ac-bb480a5082d9.png)

I'm going to see what can be done, but may need to roll this back for now.

**Comment by ferventcoder** [comment]
The site was rolled back to the previous release. Priority dropped. If you can follow up with a fix for this, we'll get that back out.

**Comment by AdmiringWorm** [comment]
One option to have this one working as it should would be to also resize the form itself.
Which can be done in pure css by using the `:focus-within` pseudo-class.
Unfortunately, only Firefox, Chrome and Safari supports that one though: https://caniuse.com/#search=focus-within

Otherwise, would need to make use of javascript I believe (possibly just as a polyfill).

**Comment by derickbailey** [comment]
sorry about that. i see the problem and will have a fix ASAP

**Comment by derickbailey** [comment]
fixed in #545

**Comment by derickbailey** [comment]
the fix was even simpler than that... i had the div width set to 100% and it didn't need to be. just needed to float right, and set the right-hand offset :)

**Comment by ferventcoder** [comment]
This fix is being released now.

**Comment by David263** [comment]
It is October, and I downloaded the latest version, and this bug (Welcome to the Chocolatey Community Package Repository!) is still happening. Doesn't bode well for using this Chocolatey thing.

**Comment by David263** [comment]
My version seems to be v0.10.11, according to Noop Mode.
